<h2>Statistics<h2>
<h3>Words<h3>
<div class="well">
    <ol id="statistics">
        <p>Loading ...</p>
    </ol>
</div>

<h3>Letters<h3>
<div id="statistics_letters" class="row">
    <p>Loading ...</p>
</div>

<script type="text/javascript">
$(function() {
    // Load stats
    $.get("stats/ranking", function(data) {
        var words = $("#statistics");
        words.empty();
        data.forEach(function(element) {
            console.log(element);
            value = element.value
            if (value == null) { value = ''; }

            words.append("<li>" + value + "</li>");
        });
    });
    $.get("stats/letters", function(data) {
        var letters = $("#statistics_letters");
        letters.empty();
        data.forEach(function(element) {
            console.log(element);
            letters.append("<div class='col-sm-6'><b>" + element.letter.toUpperCase() + "</b>: <span class='badge'>" + element.value + "</span></div>")
        });
    });
});
</script>
