apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calcwords
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: calcwords
    spec:
      containers:
      - name: calcwords
        image: kidk/training-images-calc_words
        imagePullPolicy: Always
        env:
        - name: DATABASE_HOST
          value: mysql
        - name: REDIS_HOST
          value: redis
        - name: LOOP
          value: "True"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"

