apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: generator
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
      - name: generator
        image: kidk/training-images-generator
        imagePullPolicy: Always
        env:
        - name: WEB_HOST
          value: web
        - name: RECEIVER_HOST
          value: receiver
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits:
            memory: "128Mi"
            cpu: "120m"
