apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: generator
  namespace: coscale-micro
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
      - name: generator
        image: kidk/training-images-generator
        imagePullPolicy: Always
        env:
        - name: WEB_HOST
          value: web
        - name: RECEIVER_HOST
          value: receiver
